name: Push Release File to Another Repository

on:
  release:
    types: [created]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download release asset
        id: download
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'abhishakedahal/listing-react'
          version: 'tags/${{ github.event.release.tag_name }}'
          file: 'zakra.zip'
          token: ${{ secrets.TEST }}

      - name: Push to another repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DESTINATION_PATH }}
          repository: https://github.com/abhishakedahal/listing-zip
          directory: .
          commit_message: "New release file from ${{ github.repository }}"
