name: Push Release File to Another Repository

on:
  release:
    types: [created]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download release asset
        id: download
        uses: robinraju/release-downloader@v1.9
        with:
          latest: true
          fileName: "zakra.zip"

      - name: Push to another repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DESTINATION_PATH }}
          repository: https://github.com/abhishakedahal/listing-zip
          directory: .
          commit_message: "New release file from ${{ github.repository }}"
