name: Sync Dist Folder

on:
  push:
    branches:
      - master

jobs:
  sync-dist-folder:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
      
      - name: Copy dist folder
        run: cp -r dist/ $HOME/dist
        
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: abhishakedahal/listing-zip
          repo-token: ${{ secrets.ABHISHEK }}
          ref: master
      
      - name: Commit and push dist folder
        run: |
           git config user.name 'GitHub Actions'
            git config user.email 'actions@github.com'
            cp -r $HOME/dist/* .
            git add .
            git commit -m "Sync dist folder"
            git push origin HEAD:master
